version: '3'

services:
  web:
    build: .
    container_name: papapay-http
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app_net

  db:
    image: postgres:16.1
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", $POSTGRES_DB]
      interval: 5s
      timeout: 20s
      retries: 5
      start_period: 80s 

networks:
  app_net:
    driver: bridge

volumes:
  postgres_data:
