version: '3'

services:
  web:
    build: .
    container_name: papapay-http
    expose:
      - $GUNICORN_SERVICE_PORT
    volumes:
      - static_volume:/usr/src/app/papapay/staticfiles
    env_file:
      - .env
    networks:
      - app_net
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.25.3
    container_name: papapay-nginx-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/usr/src/app/papapay/staticfiles
    ports:
      - $NGINX_HOST_PORT:$NGINX_CONTAINER_PORT
    networks:
      - app_net
    depends_on:
      - web

  db:
    image: postgres:16.1
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", $POSTGRES_DB]
      interval: 5s
      timeout: 20s
      retries: 5
      start_period: 80s 

networks:
  app_net:
    driver: bridge

volumes:
  postgres_data:
  static_volume: