# Generated by Django 4.2.7 on 2023-12-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal_address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='international_call_prefix',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
