# Generated by Django 4.2.7 on 2023-12-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postal_address', '0002_country_international_call_prefix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='initials',
            new_name='alpha3_code',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='initials',
            new_name='abbreviation',
        ),
    ]
