# Generated by Django 5.0 on 2024-01-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postal_address', '0004_country_alpha2_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='street',
            unique_together={('zip_code', 'name', 'district')},
        ),
    ]
