# Generated by Django 4.2.7 on 2023-12-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialmediaaccount',
            unique_together={('platform', 'username')},
        ),
    ]
