# Generated by Django 4.2.7 on 2023-12-18 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('postal_address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phone_numbers', to='postal_address.country')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='common_phon_content_7261e4_idx')],
                'unique_together': {('country', 'phone_number')},
            },
        ),
    ]
