# Generated by Django 4.2.7 on 2023-12-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='phonenumber',
            name='common_phon_content_7261e4_idx',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='object_id',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='content_type',
            new_name='owner_type',
        ),
        migrations.AddIndex(
            model_name='phonenumber',
            index=models.Index(fields=['owner_id', 'owner_id'], name='common_phon_owner_i_7a40b3_idx'),
        ),
    ]
