# Generated by Django 5.0 on 2024-01-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0002_remove_phonenumber_common_phon_content_7261e4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=150)),
                ('url_name', models.CharField(max_length=150)),
                ('permissions', models.ManyToManyField(to='auth.permission')),
            ],
            options={
                'verbose_name_plural': 'Page accesses',
            },
        ),
    ]
