# Generated by Django 5.0 on 2024-02-03 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_pageaccess'),
        ('restaurant', '0003_alter_restaurant_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='phonenumber',
            name='common_phon_owner_i_7a40b3_idx',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='owner_type',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='owner_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='owner_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant'),
        ),
    ]
